version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  # NOWY SERWIS: INGESTOR
  ingestor:
    build: ./backend # Używa tego samego obrazu co backend
    command: ["python", "app/ingestor.py"]
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # Zmieniamy port na 5173, domyślny dla Vite
    volumes:
      - ./frontend:/app
      - /app/node_modules # Zapobiega nadpisywaniu node_modules
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: timescale/timescaledb:2.11.0-pg15
    environment:
      POSTGRES_USER: fxuser
      POSTGRES_PASSWORD: fxpass
      POSTGRES_DB: fxdb
    ports:
      - "5432:5432"
