version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/model/model.pkl
    volumes:
      - ./backend:/app
    depends_on:
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  postgres:
    image: timescale/timescaledb:2.11.0-pg15
    environment:
      POSTGRES_USER: fxuser
      POSTGRES_PASSWORD: fxpass
      POSTGRES_DB: fxdb
    ports:
      - "5432:5432"
